# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReseptiGUI1.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(927, 958)
        MainWindow.setMouseTracking(False)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.nimiLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.nimiLabel.setObjectName("nimiLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nimiLabel)
        self.storageName = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.storageName.setReadOnly(True)
        self.storageName.setClearButtonEnabled(False)
        self.storageName.setObjectName("storageName")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.storageName)
        self.mRLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.mRLabel.setObjectName("mRLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mRLabel)
        self.storageQuantity = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.storageQuantity.setObjectName("storageQuantity")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.storageQuantity)
        self.yksikkLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.yksikkLabel.setObjectName("yksikkLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.yksikkLabel)
        self.storageUnit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.storageUnit.setObjectName("storageUnit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.storageUnit)
        self.buttonSaveStorageInfo = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.buttonSaveStorageInfo.setDefault(False)
        self.buttonSaveStorageInfo.setObjectName("buttonSaveStorageInfo")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.buttonSaveStorageInfo)
        self.buttonPopulateStorage = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.buttonPopulateStorage.setObjectName("buttonPopulateStorage")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.buttonPopulateStorage)
        self.storageTable = QtWidgets.QTableWidget(self.splitter)
        self.storageTable.setStatusTip("")
        self.storageTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.storageTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.storageTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.storageTable.setObjectName("storageTable")
        self.storageTable.setColumnCount(0)
        self.storageTable.setRowCount(0)
        self.storageTable.horizontalHeader().setCascadingSectionResizes(False)
        self.storageTable.horizontalHeader().setMinimumSectionSize(35)
        self.storageTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.nimiLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.nimiLabel_2.setObjectName("nimiLabel_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nimiLabel_2)
        self.ingredientName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.ingredientName.setReadOnly(False)
        self.ingredientName.setObjectName("ingredientName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ingredientName)
        self.tiheysLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.tiheysLabel.setObjectName("tiheysLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tiheysLabel)
        self.ingredientDensity = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.ingredientDensity.setObjectName("ingredientDensity")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ingredientDensity)
        self.allergeenitLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.allergeenitLabel.setObjectName("allergeenitLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.allergeenitLabel)
        self.ingredientAllergens = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.ingredientAllergens.setObjectName("ingredientAllergens")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ingredientAllergens)
        self.reseptiLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.reseptiLabel.setObjectName("reseptiLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.reseptiLabel)
        self.ingredientRecipe = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.ingredientRecipe.setObjectName("ingredientRecipe")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ingredientRecipe)
        self.buttonSaveIngredientInfo = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.buttonSaveIngredientInfo.setObjectName("buttonSaveIngredientInfo")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.buttonSaveIngredientInfo)
        self.buttonPopulateIngredients = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.buttonPopulateIngredients.setObjectName("buttonPopulateIngredients")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.buttonPopulateIngredients)
        self.ingredientsTable = QtWidgets.QTableWidget(self.splitter_2)
        self.ingredientsTable.setLineWidth(1)
        self.ingredientsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ingredientsTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.ingredientsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ingredientsTable.setObjectName("ingredientsTable")
        self.ingredientsTable.setColumnCount(0)
        self.ingredientsTable.setRowCount(0)
        self.ingredientsTable.horizontalHeader().setMinimumSectionSize(35)
        self.ingredientsTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.nimiLabel_3 = QtWidgets.QLabel(self.tab_3)
        self.nimiLabel_3.setObjectName("nimiLabel_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nimiLabel_3)
        self.recipeName = QtWidgets.QLineEdit(self.tab_3)
        self.recipeName.setObjectName("recipeName")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.recipeName)
        self.lopputulosLabel = QtWidgets.QLabel(self.tab_3)
        self.lopputulosLabel.setObjectName("lopputulosLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lopputulosLabel)
        self.recipeOutcomeSize = QtWidgets.QLineEdit(self.tab_3)
        self.recipeOutcomeSize.setObjectName("recipeOutcomeSize")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.recipeOutcomeSize)
        self.yksikkLabel_2 = QtWidgets.QLabel(self.tab_3)
        self.yksikkLabel_2.setObjectName("yksikkLabel_2")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.yksikkLabel_2)
        self.recipeOutcomeUnit = QtWidgets.QLineEdit(self.tab_3)
        self.recipeOutcomeUnit.setObjectName("recipeOutcomeUnit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.recipeOutcomeUnit)
        self.aikaLabel = QtWidgets.QLabel(self.tab_3)
        self.aikaLabel.setObjectName("aikaLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.aikaLabel)
        self.recipeTime = QtWidgets.QLineEdit(self.tab_3)
        self.recipeTime.setObjectName("recipeTime")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.recipeTime)
        self.buttonSaveRecipesInfo = QtWidgets.QPushButton(self.tab_3)
        self.buttonSaveRecipesInfo.setObjectName("buttonSaveRecipesInfo")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.buttonSaveRecipesInfo)
        self.buttonPopulateRecipes = QtWidgets.QPushButton(self.tab_3)
        self.buttonPopulateRecipes.setObjectName("buttonPopulateRecipes")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.buttonPopulateRecipes)
        self.buttonCreateNewRecipe = QtWidgets.QPushButton(self.tab_3)
        self.buttonCreateNewRecipe.setObjectName("buttonCreateNewRecipe")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.buttonCreateNewRecipe)
        self.gridLayout.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.recipesTable = QtWidgets.QTableWidget(self.tab_3)
        self.recipesTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.recipesTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.recipesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.recipesTable.setObjectName("recipesTable")
        self.recipesTable.setColumnCount(0)
        self.recipesTable.setRowCount(0)
        self.recipesTable.horizontalHeader().setMinimumSectionSize(35)
        self.recipesTable.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.recipesTable, 0, 1, 1, 3)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.raakaAineLabel_2 = QtWidgets.QLabel(self.tab_3)
        self.raakaAineLabel_2.setObjectName("raakaAineLabel_2")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.raakaAineLabel_2)
        self.recipeIngredientName = QtWidgets.QLineEdit(self.tab_3)
        self.recipeIngredientName.setText("")
        self.recipeIngredientName.setReadOnly(True)
        self.recipeIngredientName.setObjectName("recipeIngredientName")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.recipeIngredientName)
        self.mRLabel_2 = QtWidgets.QLabel(self.tab_3)
        self.mRLabel_2.setObjectName("mRLabel_2")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mRLabel_2)
        self.recipeIngredientQuantity = QtWidgets.QLineEdit(self.tab_3)
        self.recipeIngredientQuantity.setObjectName("recipeIngredientQuantity")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.recipeIngredientQuantity)
        self.yksikkLabel_3 = QtWidgets.QLabel(self.tab_3)
        self.yksikkLabel_3.setObjectName("yksikkLabel_3")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.yksikkLabel_3)
        self.recipeIngredientUnit = QtWidgets.QLineEdit(self.tab_3)
        self.recipeIngredientUnit.setObjectName("recipeIngredientUnit")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.recipeIngredientUnit)
        self.buttonSaveRecipeIngredient = QtWidgets.QPushButton(self.tab_3)
        self.buttonSaveRecipeIngredient.setObjectName("buttonSaveRecipeIngredient")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.buttonSaveRecipeIngredient)
        self.buttonDeleteRecipeIngredient = QtWidgets.QPushButton(self.tab_3)
        self.buttonDeleteRecipeIngredient.setObjectName("buttonDeleteRecipeIngredient")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.buttonDeleteRecipeIngredient)
        self.buttonNewRecipeIngredient = QtWidgets.QPushButton(self.tab_3)
        self.buttonNewRecipeIngredient.setObjectName("buttonNewRecipeIngredient")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.buttonNewRecipeIngredient)
        self.gridLayout.addLayout(self.formLayout_9, 1, 0, 1, 1)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.ohjeLabel = QtWidgets.QLabel(self.tab_3)
        self.ohjeLabel.setObjectName("ohjeLabel")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ohjeLabel)
        self.buttonSaveRecipeInstruction = QtWidgets.QPushButton(self.tab_3)
        self.buttonSaveRecipeInstruction.setObjectName("buttonSaveRecipeInstruction")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.buttonSaveRecipeInstruction)
        self.buttonDeleteRecipeInstruction = QtWidgets.QPushButton(self.tab_3)
        self.buttonDeleteRecipeInstruction.setObjectName("buttonDeleteRecipeInstruction")
        self.formLayout_10.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.buttonDeleteRecipeInstruction)
        self.buttonNewRecipeInstruction = QtWidgets.QPushButton(self.tab_3)
        self.buttonNewRecipeInstruction.setObjectName("buttonNewRecipeInstruction")
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.buttonNewRecipeInstruction)
        self.recipeInstruction = QtWidgets.QPlainTextEdit(self.tab_3)
        self.recipeInstruction.setObjectName("recipeInstruction")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.recipeInstruction)
        self.gridLayout.addLayout(self.formLayout_10, 1, 2, 1, 1)
        self.recipeIngredientsTable = QtWidgets.QTableWidget(self.tab_3)
        self.recipeIngredientsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.recipeIngredientsTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.recipeIngredientsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.recipeIngredientsTable.setObjectName("recipeIngredientsTable")
        self.recipeIngredientsTable.setColumnCount(0)
        self.recipeIngredientsTable.setRowCount(0)
        self.recipeIngredientsTable.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.recipeIngredientsTable, 1, 1, 1, 1)
        self.recipeInstructionsTable = QtWidgets.QTableWidget(self.tab_3)
        self.recipeInstructionsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.recipeInstructionsTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.recipeInstructionsTable.setObjectName("recipeInstructionsTable")
        self.recipeInstructionsTable.setColumnCount(0)
        self.recipeInstructionsTable.setRowCount(0)
        self.recipeInstructionsTable.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.recipeInstructionsTable, 1, 3, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.searchName = QtWidgets.QLineEdit(self.tab_4)
        self.searchName.setObjectName("searchName")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.searchName)
        self.allergiaLabel = QtWidgets.QLabel(self.tab_4)
        self.allergiaLabel.setObjectName("allergiaLabel")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.allergiaLabel)
        self.searchAllergen = QtWidgets.QLineEdit(self.tab_4)
        self.searchAllergen.setObjectName("searchAllergen")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.searchAllergen)
        self.lYtyyNLabel = QtWidgets.QLabel(self.tab_4)
        self.lYtyyNLabel.setObjectName("lYtyyNLabel")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lYtyyNLabel)
        self.puuttuuNLabel = QtWidgets.QLabel(self.tab_4)
        self.puuttuuNLabel.setObjectName("puuttuuNLabel")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.puuttuuNLabel)
        self.searchIngredient = QtWidgets.QLineEdit(self.tab_4)
        self.searchIngredient.setObjectName("searchIngredient")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.searchIngredient)
        self.nimiLabel_4 = QtWidgets.QLabel(self.tab_4)
        self.nimiLabel_4.setObjectName("nimiLabel_4")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nimiLabel_4)
        self.raakaAineLabel = QtWidgets.QLabel(self.tab_4)
        self.raakaAineLabel.setObjectName("raakaAineLabel")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.raakaAineLabel)
        self.buttonSearch = QtWidgets.QPushButton(self.tab_4)
        self.buttonSearch.setObjectName("buttonSearch")
        self.formLayout_5.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.buttonSearch)
        self.spinMissingN = QtWidgets.QSpinBox(self.tab_4)
        self.spinMissingN.setObjectName("spinMissingN")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinMissingN)
        self.spinFoundN = QtWidgets.QSpinBox(self.tab_4)
        self.spinFoundN.setMinimum(1)
        self.spinFoundN.setObjectName("spinFoundN")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.spinFoundN)
        self.checkAllergen = QtWidgets.QCheckBox(self.tab_4)
        self.checkAllergen.setObjectName("checkAllergen")
        self.formLayout_5.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.checkAllergen)
        self.checkName = QtWidgets.QCheckBox(self.tab_4)
        self.checkName.setObjectName("checkName")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.checkName)
        self.checkIngredient = QtWidgets.QCheckBox(self.tab_4)
        self.checkIngredient.setObjectName("checkIngredient")
        self.formLayout_5.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.checkIngredient)
        self.checkMissingN = QtWidgets.QCheckBox(self.tab_4)
        self.checkMissingN.setObjectName("checkMissingN")
        self.formLayout_5.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.checkMissingN)
        self.checkFoundN = QtWidgets.QCheckBox(self.tab_4)
        self.checkFoundN.setObjectName("checkFoundN")
        self.formLayout_5.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.checkFoundN)
        self.horizontalLayout_5.addLayout(self.formLayout_5)
        self.searchTable = QtWidgets.QTableWidget(self.tab_4)
        self.searchTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.searchTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.searchTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.searchTable.setObjectName("searchTable")
        self.searchTable.setColumnCount(0)
        self.searchTable.setRowCount(0)
        self.searchTable.horizontalHeader().setMinimumSectionSize(35)
        self.searchTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_5.addWidget(self.searchTable)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame = QtWidgets.QFrame(self.tab_5)
        self.frame.setGeometry(QtCore.QRect(30, 290, 861, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 502, 197))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.buttonLoadAll = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonLoadAll.setObjectName("buttonLoadAll")
        self.verticalLayout_2.addWidget(self.buttonLoadAll)
        self.buttonLoadIngredients = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonLoadIngredients.setObjectName("buttonLoadIngredients")
        self.verticalLayout_2.addWidget(self.buttonLoadIngredients)
        self.buttonLoadRecipes = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonLoadRecipes.setObjectName("buttonLoadRecipes")
        self.verticalLayout_2.addWidget(self.buttonLoadRecipes)
        self.buttonLoadStorage = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonLoadStorage.setObjectName("buttonLoadStorage")
        self.verticalLayout_2.addWidget(self.buttonLoadStorage)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.buttonSaveAll = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonSaveAll.setObjectName("buttonSaveAll")
        self.verticalLayout.addWidget(self.buttonSaveAll)
        self.buttonSaveIngredients = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonSaveIngredients.setObjectName("buttonSaveIngredients")
        self.verticalLayout.addWidget(self.buttonSaveIngredients)
        self.buttonSaveRecipes = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonSaveRecipes.setObjectName("buttonSaveRecipes")
        self.verticalLayout.addWidget(self.buttonSaveRecipes)
        self.buttonSaveStorage = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonSaveStorage.setObjectName("buttonSaveStorage")
        self.verticalLayout.addWidget(self.buttonSaveStorage)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Älykäs reseptikirja"))
        self.nimiLabel.setText(_translate("MainWindow", "Nimi"))
        self.mRLabel.setText(_translate("MainWindow", "Määrä"))
        self.yksikkLabel.setText(_translate("MainWindow", "Yksikkö"))
        self.buttonSaveStorageInfo.setText(_translate("MainWindow", "Tallenna"))
        self.buttonPopulateStorage.setText(_translate("MainWindow", "Päivitä lista"))
        self.storageTable.setToolTip(_translate("MainWindow", "<html><head/><body><p>Varastossa olevat tuotteet</p></body></html>"))
        self.storageTable.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Varastossa olevat tuotteet</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Varasto"))
        self.nimiLabel_2.setText(_translate("MainWindow", "Nimi"))
        self.tiheysLabel.setText(_translate("MainWindow", "Tiheys"))
        self.allergeenitLabel.setText(_translate("MainWindow", "Allergeenit"))
        self.reseptiLabel.setText(_translate("MainWindow", "Resepti"))
        self.buttonSaveIngredientInfo.setText(_translate("MainWindow", "Tallenna"))
        self.buttonPopulateIngredients.setText(_translate("MainWindow", "Päivitä lista"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Raaka-aineet"))
        self.nimiLabel_3.setText(_translate("MainWindow", "Nimi"))
        self.lopputulosLabel.setText(_translate("MainWindow", "Lopputulos"))
        self.yksikkLabel_2.setText(_translate("MainWindow", "Yksikkö"))
        self.aikaLabel.setText(_translate("MainWindow", "Aika"))
        self.buttonSaveRecipesInfo.setText(_translate("MainWindow", "Tallenna"))
        self.buttonPopulateRecipes.setText(_translate("MainWindow", "Päivitä lista"))
        self.buttonCreateNewRecipe.setText(_translate("MainWindow", "Uusi resepti"))
        self.raakaAineLabel_2.setText(_translate("MainWindow", "Raaka-aine"))
        self.mRLabel_2.setText(_translate("MainWindow", "Määrä"))
        self.yksikkLabel_3.setText(_translate("MainWindow", "Yksikkö"))
        self.buttonSaveRecipeIngredient.setText(_translate("MainWindow", "Tallenna"))
        self.buttonDeleteRecipeIngredient.setText(_translate("MainWindow", "Poista valittu"))
        self.buttonNewRecipeIngredient.setText(_translate("MainWindow", "Lisää uusi"))
        self.ohjeLabel.setText(_translate("MainWindow", "Ohje"))
        self.buttonSaveRecipeInstruction.setText(_translate("MainWindow", "Tallenna"))
        self.buttonDeleteRecipeInstruction.setText(_translate("MainWindow", "Poista valittu"))
        self.buttonNewRecipeInstruction.setText(_translate("MainWindow", "Lisää uusi"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Reseptit"))
        self.allergiaLabel.setText(_translate("MainWindow", "Allergeeni"))
        self.lYtyyNLabel.setText(_translate("MainWindow", "Löytyy N"))
        self.puuttuuNLabel.setText(_translate("MainWindow", "Puuttuu N"))
        self.nimiLabel_4.setText(_translate("MainWindow", "Nimi"))
        self.raakaAineLabel.setText(_translate("MainWindow", "Raaka-aine"))
        self.buttonSearch.setText(_translate("MainWindow", "Hae valituilla hakuehdoilla"))
        self.checkAllergen.setText(_translate("MainWindow", "Ei allergeenia"))
        self.checkName.setText(_translate("MainWindow", "Nimi"))
        self.checkIngredient.setText(_translate("MainWindow", "Raaka-aine"))
        self.checkMissingN.setText(_translate("MainWindow", "Puuttuu N"))
        self.checkFoundN.setText(_translate("MainWindow", "Löytyy N"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Haku"))
        self.label_2.setText(_translate("MainWindow", "Lataa uudelleen"))
        self.buttonLoadAll.setText(_translate("MainWindow", "Kaikki"))
        self.buttonLoadIngredients.setText(_translate("MainWindow", "Raaka-aineet"))
        self.buttonLoadRecipes.setText(_translate("MainWindow", "Reseptit"))
        self.buttonLoadStorage.setText(_translate("MainWindow", "Varastotilanne"))
        self.label_3.setText(_translate("MainWindow", "Tallenna"))
        self.buttonSaveAll.setText(_translate("MainWindow", "Kaikki"))
        self.buttonSaveIngredients.setText(_translate("MainWindow", "Raaka-aineet"))
        self.buttonSaveRecipes.setText(_translate("MainWindow", "Reseptit"))
        self.buttonSaveStorage.setText(_translate("MainWindow", "Varastotilanne"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Asetukset"))

